const Cities = [
  "Jerusalem",
  "Tel Aviv",
  "Haifa",
  "Rishon LeZion",
  "Petah Tikva",
  "Ashdod",
  "Netanya",
  "Beer Sheva",
  "Holon",
  "Bnei Brak",
  "Ramat Gan",
  "Ashkelon",
  "Bat Yam",
  "Herzliya",
  "Kfar Saba",
  "Beit Shemesh",
  "Lod",
  "Netivot",
  "Tiberias",
  "Modiin-Maccabim-Reut",
  "Hadera",
  "Raanana",
  "Acre",
  "Nahariya",
  "Rehovot",
  "Nazareth",
  "Kiryat Gat",
  "Eilat",
  "Givatayim",
  "Hod HaSharon",
  "Umm al-Fahm",
  "Ramla",
  "Kiryat Shmona",
  "Maalot-Tarshiha",
  "Sakhnin",
  "Givat Shmuel",
  "Rosh HaAyin",
  "Kiryat Motzkin",
  "Ofakim",
  "Kiryat Yam",
  "Kfar Yona",
  "Yavne",
  "Dimona",
  "Nahariya",
  "Or Yehuda",
  "Zikhron Yaakov",
  "Migdal HaEmek",
];

const sortedCities = Cities.sort();

module.exports = sortedCities;
